name: snakemake_unit_tests-env
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - boost-cpp
  - yaml-cpp
  - git
# required for commitizen
  - nodejs
  - pre-commit
  - cppcheck
  - sarcasm::clang-format

  - libtool
  - automake
  - autoconf
  - make>=4.2
  - gxx_linux-64>=8.2.0
  - doxygen
  - cppunit

  - snakemake
  - pytest
  - python-magic
  - libmagic
