name: snakemake_unit_tests-env
dependencies:
  - boost-cpp
  - yaml-cpp
  - git
# required for commitizen
  - nodejs
  - pre-commit
  - cppcheck
  - sarcasm::clang-format

  - libtool
  - automake
  - autoconf
  - make>=4.2
  - clang_osx-64>=8.2.0
