name: C/C++ CI

on:
  pull_request:
    branches: [ default, dev ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: checkout_repo
        uses: actions/checkout@v2
      - name: run_cicd_docker
        run: docker run lightning-auriga/snakemake-gcc ./build_test_commands.sh
