name: C/C++ CI

on:
  pull_request:
    branches: [ default, dev ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: checkout_repo
        uses: actions/checkout@v2
      - name: activate_conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-activate-base: true
          activate-environment: ""
      - name: install_mamba
        run: conda install -y -c conda-forge mamba
      - name: install_environment
        run: mamba env create -f environment-linux.yaml
      - name: activate_environment
        uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: "snakemake_unit_tests-env"
      - name: generate
        run: ./generate.bash
      - name: configure
        run: ./configure --with-boost=$CONDA --with-boost-libdir=$CONDA/bin
      - name: build
        run: make -j2
      - name: TAP
        run: make -j2 check
      - name: unit_tests
        run: ./test_suite.out
