name: C/C++ CI

on:
  pull_request:
    branches: [ default, dev ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: checkout_repo
        uses: actions/checkout@v2
      - name: set up build environment
        run: |
          export PATH="/usr/share/miniconda/bin:$PATH"
          conda install -c conda-forge -q mamba
          mamba env create -q -f environment-linux.yaml
      - name: generate
        run: |
          export PATH="/usr/share/miniconda/bin:$PATH"
          ./generate.bash
      - name: configure
        run: |
          export PATH="/usr/share/miniconda/bin:$PATH"
          ./configure --with-boost=/usr/share/miniconda --with-boost-libdir=/usr/share/miniconda/lib
      - name: build
        run: |
          export PATH="/usr/share/miniconda/bin:$PATH"
          make -j2 CPPFLAGS=""
      - name: TAP
        run: |
          export PATH="/usr/share/miniconda/bin:$PATH"
          make -j2 check
      - name: run unit tests
        run: |
          export PATH="/usr/share/miniconda/bin:$PATH"
          ./test_suite.out
