name: C/C++ CI

on:
  pull_request:
    branches: [ default, dev ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: checkout_repo
        uses: actions/checkout@v2
      - name: run_in_docker
        uses: addnab/docker-run-action@v3
        with:
          image: cpalmer718/snakemake-gcc
          options: -v ${{ github.workspace }}:/work/snakemake_unit_tests
          run: |
            ls -l
            ./generate.bash
            ./configure --with-boost=$CONDA_PREFIX --with-boost-libdir=$CONDA_PREFIX/lib
            make -j2
            make -j2 check
            ./test_suite.out
