name: C/C++ CI

on:
  pull_request:
    branches: [ default, dev ]
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: checkout_repo
        uses: actions/checkout@v2
      - name: update host
        run: |
          sudo apt-get update
      - name: set up build environment
        run: |
          export PATH="/usr/share/miniconda/bin:$PATH"
          conda install -c conda-forge -y mamba
#          sed -i 's/  - pytest// ; s/  - python-magic// ; s/  - libmagic//' environment-linux.yaml
          mamba env create -f environment-linux.yaml
      - name: generate
        run: |
          export PATH="/usr/share/miniconda/envs/snakemake_unit_tests-env/bin:$PATH"
          ./generate.bash
      - name: configure
        run: |
          export PATH="/usr/share/miniconda/envs/snakemake_unit_tests-env/bin:$PATH"
          export LD_LIBRARY_PATH="/usr/share/miniconda/envs/snakemake_unit_tests-env/lib"
          ./configure --with-boost=/usr/share/miniconda/envs/snakemake_unit_tests-env --with-boost-libdir=/usr/share/miniconda/envs/snakemake_unit_tests-env/lib
      - name: build
        run: |
          export PATH="/usr/share/miniconda/envs/snakemake_unit_tests-env/bin:$PATH"
          export LD_LIBRARY_PATH="/usr/share/miniconda/envs/snakemake_unit_tests-env/lib"
          make -j2
          ./snakemake_unit_tests.out -h
      - name: run unit tests
        run: |
          export PATH="/usr/share/miniconda/envs/snakemake_unit_tests-env/bin:$PATH"
          export LD_LIBRARY_PATH="/usr/share/miniconda/envs/snakemake_unit_tests-env/lib"
          ./test_suite.out
      - name: run code coverage
        run: |
          export PATH="/usr/share/miniconda/envs/snakemake_unit_tests-env/bin:$PATH"
          export LD_LIBRARY_PATH="/usr/share/miniconda/envs/snakemake_unit_tests-env/lib"
          x86_64-conda-linux-gnu-gcov -r $(find snakemake_unit_tests \( -name "*gcda" -and -not -iname "*test*" \) -print)
          gcovr -g -x
          curl -Os https://uploader.codecov.io/latest/linux/codecov
          chmod +x codecov
          ./codecov
